### Get All Todos
GET http://localhost:8000/todos

### Get Todo By Id
GET http://localhost:8000/todos/66c2b783befe4fb90648e42d

### Create New Todo
POST http://localhost:8000/todos
Content-Type: application/json

{
    "title": "Todo 23",
    "content": "Content of Todo 123",
    "completed": false,
    "userId": "66bb1d2e15a88a5b9c11d25c"
}

### Update Todo
PUT http://localhost:8000/todos/66c2b783befe4fb90648e42d
Content-Type: application/json

{
    "title": "Todo 2",
    "content": "Content of Todo 2 - Edited",
    "completed": true,
    "userId": "66bb1d2e15a88a5b9c11d25c"
}

### Delete Todo
DELETE http://localhost:8000/todos/66c2b783befe4fb90648e42d
